version: "3.9"

services:
    db_node:
        image: mysql
        ports:
            - '3306:3306'
        environment:
            MYSQL_DATABASE: db_node
            MYSQL_ROOT_USER: user_node
            MYSQL_USER: user_node
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_PASSWORD: "root"

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - '8080:80'
        environment:
            PMA_HOST: db_node
            PMA_USER: user_node
            PMA_PASSWORD: "root"
        depends_on:
            - db_node
